### ISSUE TITLE
Unable to enter First Name and Last Name on Billing address Page

### ISSUE THREAD

**Issue by ibrahim89** [ssahibsingh/React_E-Commerce#4]
Steps to see the issue.
1. Go to home page
2. click on add to cart button for any product
3. click on go to checkout button on cart
4. you will see Billing address page. here try to type First Name and Last name
5. you will notice curson is not moving.

**Comment by ssahibsingh** [comment]
Thanks @ibrahim89 for bringing up this issue. Now i have resolved this. Please Check.

**Comment by ibrahim89** [comment]
Hi @ssahibsingh  it is working fine now. Thanks
